@startuml anwendungsfaelle
title Minecraft Client - Spielsitzung (Survival)

left to right direction
skinparam shadowing false

actor "Spieler" as Spieler
actor "<<System>> Microsoft/Xbox\nServices" as Auth

rectangle "Minecraft Client" as System {
  usecase "Spielsitzung (Survival)" as UCSession
}

Spieler --> UCSession
Auth --> UCSession

@enduml

